$Test="echo AGGACAACGGCCAATCGTCGTGGAGCGCGGCGCCTCCGCGGAGAGGTCCGGTCCGAATATCCCTCCGCCTTCCTCCCTCCCTCGCTCCCTCCCTGCGCGCC|grep --color GGCGCCTCCGCGGAGAGGTC";
$Answer=`$Test`;
foreach $Character ($Answer) {
	print $Character;
}
print `$Test`;
